### PR TITLE
re-add "unnecessary" normalization to fix UTF-8 errors.

### PR DESCRIPTION
**Pull request by UsernamesLame**
I forgot to remove this line yesterday, I'm not sure why it's not causing any issues having it there referencing a nonexistent variable ```samples``` but it seems like normalization wasn't required based on transcription testing I've done so far.

### CODE REVIEW

**Comment by absadiki** [comment]
Oh, I didn't notice yesterday, and I didn't run any tests. 
Next time please run the tests in the test directory before committing! 

As for this, I think normalization is important, without it sometimes I get utf-8 decode problems. 
Please fix the code to `arr /= np.iinfo(np.int16).max` and commit it so I cam merge the fix asap. 

Thanks!

**Comment by UsernamesLame** [comment]
Sorry about that. Slipped my mind to do the tests. Thankfully it didn't seem to actually break anything. That's the craziest part.

**Comment by UsernamesLame** [comment]
@abdeladim-s I re-added the normalization. I haven't had a chance to run the test suite. For now I'm relying on the CI pipeline to catch anything.

I re-added ```arr /= np.iinfo(np.int16).max```

**Comment by absadiki** [comment]
It's okey, no worries!  
I, indeed, need to include the tests in CI, for now I am just running them locally :smile: 

I'll merge this for now. 
Thanks a lot!

**Review by absadiki — APPROVED** [review]

**Pull request merged**
