### PR TITLE
adding compatibility with whisper large-v3

### PR DESCRIPTION
**Pull request by joseporiolayats**
Just changed a line so that it accepts large-v3 models, it wasn't even downloading them.

### CODE REVIEW

**Review by absadiki — CHANGES_REQUESTED** [review]
Thanks @joseporiolayats for the PR.
I think the `large` ggml model is already the `large-v3` whisper model, so there is no `large-v3` in `whisper.cpp`, instead we can change that constant to `large-v2` ?

**Comment by Govind-S-B** [comment]
lol its weird that i was going to make a PR for this just now

Also yes large is now large-v3 and large v2 need to be added , but from how the models are downloaded directly based on the name you pass in `return f"{MODELS_BASE_URL}/{MODELS_PREFIX_URL}-{model_name}.bin"` , large-v3 should be the thing as there is no large.bin
image
image



Can we have large as an alias as well for large-v3 ? If this PR doesnt reolve it ill make a PR later ig

**Review by Govind-S-B — APPROVED** [review]
thats a good one

**Comment by joseporiolayats** [comment]
Hey @abdeladim-s missed the opportunity to thank you for this package!!!

I made another commit in oder to add all the available models in the hf repo, including the quantized ones.

Hope this all goes well :)

**Comment by absadiki** [comment]
> lol its weird that i was going to make a PR for this just now
> 
> Also yes large is now large-v3 and large v2 need to be added , but from how the models are downloaded directly based on the name you pass in `return f"{MODELS_BASE_URL}/{MODELS_PREFIX_URL}-{model_name}.bin"` , large-v3 should be the thing as there is no large.bin image image
> 
> Can we have large as an alias as well for large-v3 ? If this PR doesnt reolve it ill make a PR later ig

Yeah, thanks @Govind-S-B  for pointing that out, `large-v3` is actually the right file and not `large` . 
For now, I can see @joseporiolayats took care of everything. As for the alias, if you have an idea feel free to send a PR any time.

**Comment by absadiki** [comment]
> Hey @abdeladim-s missed the opportunity to thank you for this package!!!
> 
> I made another commit in oder to add all the available models in the hf repo, including the quantized ones.
> 
> Hope this all goes well :)

Hey @joseporiolayats, Everything seems perfect. 
Thank you as well for the awesome contribution :)

**Pull request merged**
